state_choices = {
        'AB': 'Abia',
        'AD': 'Adamawa',
        'AK': 'Akwa Ibom',
        'AN': 'Anambra',
        'BA': 'Bauchi',
        'BAY': 'Bayelsa',
        'BE': 'Benue',
        'BO': 'Borno',
        'CR': 'Cross River',
        'DE': 'Delta',
        'EB': 'Ebonyi',
        'ED': 'Edo',
        'EK': 'Ekiti',
        'EN': 'Enugu',
        'GO': 'Gombe',
        'IM': 'Imo',
        'JI': 'Jigawa',
        'KD': 'Kaduna',
        'KA': 'Kano',
        'KT': 'Katsina',
        'KE': 'Kebbi',
        'KO': 'Kogi',
        'KW': 'Kwara',
        'LAG': 'Lagos',
        'NAS': 'Nasarawa',
        'NIG': 'Niger',
        'OGU': 'Ogun',
        'OND': 'Ondo',
        'OSU': 'Osun',
        'OYO': 'Oyo',
        'PLA': 'Plateau',
        'RIV': 'Rivers',
        'SOK': 'Sokoto',
        'TAR': 'Taraba',
        'YOB': 'Yobe',
        'ZAM': 'Zamfara',
        'FCT': 'Abuja',
}

type_choices = {
    'HW': 'Highway',
    'RC': 'Re-const',
    'BU': 'Building',
    'RO': 'Roads',
    'RB': 'Road & Bridge',
    'RE': 'Rehabilitation',
    'CO': 'Completion',
}