state_choices = {
        'AB': 'Abia',
        'AD': 'Adamawa',
        'AK': 'Akwa Ibom',
        'AN': 'Anambra',
        'BA': 'Bauchi',
        'BY': 'Bayelsa',
        'BE': 'Benue',
        'BO': 'Borno',
        'CR': 'Cross River',
        'DE': 'Delta',
        'EB': 'Ebonyi',
        'ED': 'Edo',
        'EK': 'Ekiti',
        'EN': 'Enugu',
        'GO': 'Gombe',
        'IM': 'Imo',
        'JI': 'Jigawa',
        'KD': 'Kaduna',
        'KA': 'Kano',
        'KT': 'Katsina',
        'KE': 'Kebbi',
        'KO': 'Kogi',
        'KW': 'Kwara',
        'LG': 'Lagos',
        'NS': 'Nasarawa',
        'NG': 'Niger',
        'OG': 'Ogun',
        'OD': 'Ondo',
        'OS': 'Osun',
        'OY': 'Oyo',
        'PL': 'Plateau',
        'RI': 'Rivers',
        'SK': 'Sokoto',
        'TR': 'Taraba',
        'YO': 'Yobe',
        'ZM': 'Zamfara',
        'FCT': 'Abuja',
}

type_con_choices = {
    'HW': 'Highway',
    'RC': 'Re-const',
    'BU': 'Building',
    'RO': 'Roads',
    'RB': 'Road & Bridge',
    'RE': 'Rehabilitation',
    'CO': 'Completion',
}