# Generated by Django 3.1.5 on 2021-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
