# Generated by Django 3.1.5 on 2021-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210131_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='type_con',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
