# Generated by Django 3.1.5 on 2021-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210202_1641'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='project',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
