# Generated by Django 3.1.5 on 2021-02-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210203_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
