# Generated by Django 3.1.5 on 2021-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210203_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hectares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
