# Generated by Django 3.1.5 on 2021-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
